import { defineConfig } from "tsup";
export default defineConfig([
    {
        entry: ["src/index.ts"],
        format: ["esm", "cjs", "iife"],
        dts: true,
        splitting: true,
        sourcemap: true,
        globalName: "FastEventSpaces",
        clean: true,
        treeshake: true,
        minify: true,
    },
    {
        entry: ["src/executors/index.ts"],
        outDir: "dist/executors",
        format: ["esm", "cjs"],
        dts: true,
        splitting: true,
        sourcemap: true,
        clean: true,
        treeshake: true,
        minify: true,
    },
    {
        entry: ["src/pipes/index.ts"],
        outDir: "dist/pipes",
        format: ["esm", "cjs"],
        dts: true,
        splitting: true,
        sourcemap: true,
        clean: true,
        treeshake: true,
        minify: true,
    },
    {
        // FastLiteEvent 轻量级事件发射器（独立入口，不进入主 bundle）
        entry: ["src/liteEvent.ts"],
        outDir: "dist",
        format: ["esm", "cjs", "iife"],
        dts: true,
        splitting: true,
        sourcemap: true,
        globalName: "FastLiteEvent",
        // outDir 与 index 共用 dist，禁用 clean 避免清掉其他入口的产物
        clean: false,
        treeshake: true,
        minify: true,
    },
]);
