import { defineConfig } from "tsup";
export default defineConfig([
    {
        entry: ["src/index.ts"],
        format: ["esm", "cjs", "iife"],
        dts: true,
        splitting: true,
        sourcemap: true,
        globalName: "FastEventSpaces",
        clean: true,
        treeshake: true,
        minify: true,
    },
    {
        entry: ["src/executors/index.ts"],
        outDir: "dist/executors",
        format: ["esm", "cjs"],
        dts: true,
        splitting: true,
        sourcemap: true,
        clean: true,
        treeshake: true,
        minify: true,
    },
    {
        entry: ["src/pipes/index.ts"],
        outDir: "dist/pipes",
        format: ["esm", "cjs"],
        dts: true,
        splitting: true,
        sourcemap: true,
        clean: true,
        treeshake: true,
        minify: true,
    },
]);
